apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: app
spec:
  template:
    serviceAccountName: argo-events
  dependencies:
    - name: app
      eventSourceName: app
      eventName: app
  triggers:
    - template:
        name: github-actions
        http:
          url: https://api.github.com/repos/vfarcic/argo-events-gh-demo/dispatches
          method: POST
          payload:
            - src:
                dependencyName: app
                dataKey: body.metadata.labels.actions\.github\.com\/name
              dest: event_type
            - src:
                dependencyName: app
                dataKey: body
              dest: client_payload.resource
          headers:
            Accept: "application/vnd.github.everest-preview+json"
          secureHeaders:
            - name: Authorization
              valueFrom:
                secretKeyRef:
                  name: github
                  key: token
      retryStrategy:
        steps: 3
      policy:
        status:
          allow:
            - 200
            - 201
            - 204
